import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { BookOpenIcon, CalendarDateRangeIcon, CircleStackIcon, HeartIcon, HomeIcon, UsersIcon } from "@heroicons/react/16/solid";
import MenuItem from "@/components/menu-item";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <nav className="shadow-md w-full py-4">
          <div className="px-8 w-full flex justify-between">
            <a href="/" className="text-lg font-bold">Simple CRUD</a>

            <div className="flex justify-end">
              <MenuItem name="Registrations" href="registrations" icon={<CircleStackIcon className="w-6 me-2" />} />
              <MenuItem name="Students" href="students" icon={<UsersIcon className="w-6 me-2"/>} />
              <MenuItem name="Classes" href="sections" icon={<CalendarDateRangeIcon className="w-6 me-2" />} />
              <MenuItem name="Courses" href="courses" icon={<BookOpenIcon className="w-6 me-2" />} />
            </div>
          </div>

        </nav>

        <main className="px-8 pt-4">
          {children}
        </main>
      </body>
    </html>
  );
}
