import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/side-nav";
import Title from "antd/es/typography/Title";
import { Layout } from "antd";
import { Content, Header } from "antd/es/layout/layout";
import Sider from "antd/es/layout/Sider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <Layout className="h-full" >
          <Header className="p-0 mx-0 mb-4 flex items-center justify-between px-6 bg-white">
            <h1 className="text-xl">Using Ant Design</h1>
          </Header>

          <div className="flex mx-4 gap-4 h-full">
            
            <SideNav />

            <main>
              {children}
            </main>
          </div>
        </Layout>
      </body>
    </html>
  );
}
