networks:
  simple-net:

volumes:
  simple-volume:

services:
  db:
    image: postgres:alpine
    container_name: simple-db
    environment:
      - TZ=Asia/Yangon
      - POSTGRES_USER=simple
      - POSTGRES_PASSWORD=simple
      - POSTGRES_DB=simple
    networks:
      - simple-net
    ports:
      - 5432:5432
    volumes:
      - simple-volume:/var/lib/postgresql/data